configName: pic32cm_mc00_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32CM1216MC00048
projectName: ''
settings:
  PackageFilter: classb_pic32cm_mc;classb_sam_e5x_d5x;csp;csp_apps_sam_c20_c21;csp_apps_sam_e70_s70_v70_v71
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.2.52\PIC32CM1216MC00048\atdf\PIC32CM1216MC00048.atdf
