format_version: v1.0
type: UniqueComponent
attributes: {id: lib_classb_pic32cm_mc}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CLASSB_CLOCK_TEST_DURATION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: CLASSB_CLOCK_TEST_OPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: CLASSB_CLOCK_TEST_PERCENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: CLASSB_CPU_TEST_OPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CLASSB_FLASH_CRC_CONF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: CLASSB_INTERRUPT_TEST_OPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: CLASSB_SOURCE_CPUTEST_S}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /templates/pic32cm_mc/classb_cpu_reg_test_keil.S.ftl}
  - type: File
    attributes: {id: CLASSB_SOURCE_RESULT_MGMT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /templates/pic32cm_mc/classb_result_management_keil.S.ftl}
  - type: KeyValueSet
    attributes: {id: CLASSB_SRAM_MARCH_ALGORITHM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: CLASSB_SRAM_MARCH_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: CLASSB_SRAM_TEST_OPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CLASSB_TOOLCHAIN_SEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_classb_pic32cm_mc, value: '2'}
- type: ElementPosition
  attributes: {x: '173', y: '78', id: lib_classb_pic32cm_mc}
