configName: pic32cm_mc00_curiosity_pro
folderName: ''
format_version: null
frameworkPath: E:\H3_dev
processor: PIC32CM1216MC00048
projectName: classb_api_usage
settings:
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  DFPPath: .\dev_packs\Microchip\PIC32CM-MC_DFP\1.2.52\PIC32CM1216MC00048\atdf\PIC32CM1216MC00048.atdf
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  MERGE_STRATEGY: USER_ALL
  PackageFilter: bsp;classb_pic32cm_mc;classb_sam_e5x_d5x;csp;csp_apps_sam_c20_c21;csp_apps_sam_e70_s70_v70_v71
  TRUSTZONE: 'false'
